# integrate_debug_gem.cmake
#
# Ruby 3.1.1 ships the `debug` gem (rdbg / ruby/debug) as a BUNDLED gem with a
# C extension under .bundle/gems/debug-1.4.0/ext/debug/. When Ruby is built
# with --with-static-linked-ext, tool/rbinstall.rb explicitly skips bundled
# gems that have a C extension (see rbinstall.rb: "skip installation of
# debug 1.4.0; bundled gem with an extension library is not supported on
# --with-static-linked-ext"), so the gem is dropped entirely from staging.
#
# To make `require 'debug/open'` work in the embedded VM, we promote the
# debug gem to a first-class Ruby extension by copying its sources into
# ext/debug/ BEFORE configure runs. Ruby's extmk.rb auto-discovers it via
# Dir.glob("ext/**/extconf.rb") and statically links it like socket /
# io/console / objspace.
#
# The companion script install_debug_gem_lib.cmake handles the pure-Ruby
# half of the gem post-install.
#
# Required variables:
#   RUBY_SOURCE_DIR  - Ruby source root (after extraction + patches)

cmake_minimum_required(VERSION 3.14)

foreach(VAR RUBY_SOURCE_DIR)
    if(NOT DEFINED ${VAR})
        message(FATAL_ERROR "integrate_debug_gem.cmake: ${VAR} is required")
    endif()
endforeach()

# Auto-detect the bundled debug gem dir from the Ruby source tree. Ruby ships
# exactly one debug-<X.Y.Z>/ here; the version is coupled to the Ruby release
# (3.1.1 → 1.4.0, 3.2.x → 1.7+, etc.) and pinning a literal would silently
# break the build when Ruby is upgraded.
file(GLOB _DEBUG_GEM_DIRS LIST_DIRECTORIES true "${RUBY_SOURCE_DIR}/.bundle/gems/debug-*")
list(LENGTH _DEBUG_GEM_DIRS _DEBUG_GEM_COUNT)
if(_DEBUG_GEM_COUNT EQUAL 0)
    message(FATAL_ERROR
        "No debug-* gem found under ${RUBY_SOURCE_DIR}/.bundle/gems/.\n"
        "If you've upgraded to a Ruby version where `debug` is no longer bundled "
        "(e.g. moved into a default gem or vendored separately), this script needs "
        "to be revisited.")
endif()
if(_DEBUG_GEM_COUNT GREATER 1)
    message(FATAL_ERROR
        "Expected exactly one debug-* gem under ${RUBY_SOURCE_DIR}/.bundle/gems/, found: ${_DEBUG_GEM_DIRS}")
endif()
list(GET _DEBUG_GEM_DIRS 0 DEBUG_GEM_DIR)
get_filename_component(_DEBUG_GEM_DIRNAME "${DEBUG_GEM_DIR}" NAME)
message(STATUS "Detected bundled debug gem: ${_DEBUG_GEM_DIRNAME}")

set(TARGET_EXT_DIR "${RUBY_SOURCE_DIR}/ext/debug")

# Idempotent: skip if already integrated. The step's ExternalProject stamp
# already gates re-runs, but this guards against partial-state rebuilds.
if(EXISTS "${TARGET_EXT_DIR}/extconf.rb")
    message(STATUS "ext/debug already present, skipping integration")
    return()
endif()

if(NOT EXISTS "${DEBUG_GEM_DIR}/ext/debug/debug.c")
    message(FATAL_ERROR
        "debug gem ext sources not found at ${DEBUG_GEM_DIR}/ext/debug/.\n"
        "The bundled gem dir was detected but its ext/debug/debug.c is missing — "
        "possibly the gem's layout changed in this Ruby version.")
endif()

message(STATUS "Integrating debug gem C extension into Ruby ext/debug/")

file(MAKE_DIRECTORY "${TARGET_EXT_DIR}")
file(COPY
    "${DEBUG_GEM_DIR}/ext/debug/debug.c"
    "${DEBUG_GEM_DIR}/ext/debug/iseq_collector.c"
    DESTINATION "${TARGET_EXT_DIR}"
)

# Extract the gem's version string and inline it into extconf.rb so the
# generated debug_version.h doesn't need to require_relative back into the
# .bundle/ tree (the original extconf.rb does `require_relative
# '../../lib/debug/version'`, which is broken once we move the ext).
if(NOT EXISTS "${DEBUG_GEM_DIR}/lib/debug/version.rb")
    message(FATAL_ERROR "debug gem version.rb not found at ${DEBUG_GEM_DIR}/lib/debug/version.rb")
endif()

file(READ "${DEBUG_GEM_DIR}/lib/debug/version.rb" _VERSION_RB)
string(REGEX MATCH "VERSION[ \t]*=[ \t]*['\"]([^'\"]+)['\"]" _ "${_VERSION_RB}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "Could not parse VERSION from ${DEBUG_GEM_DIR}/lib/debug/version.rb")
endif()
set(DEBUG_VERSION_STR "${CMAKE_MATCH_1}")

message(STATUS "  debug gem version: ${DEBUG_VERSION_STR}")

file(WRITE "${TARGET_EXT_DIR}/extconf.rb"
"# Auto-generated by ruby-for-android integrate_debug_gem.cmake.
# Statically links the debug gem's C extension into libruby-static.a.
require 'mkmf'
File.write('debug_version.h', %Q[#define RUBY_DEBUG_VERSION \"${DEBUG_VERSION_STR}\"\\n])
create_makefile 'debug/debug'
")

message(STATUS "  Wrote ${TARGET_EXT_DIR}/extconf.rb")
message(STATUS "  Wrote ${TARGET_EXT_DIR}/debug.c, iseq_collector.c")
